In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.datasets import load_digits
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [3]:
digits = load_digits()

X = digits.data
y = digits.target

In [4]:
print(X.shape)

(1797, 64)


In [5]:
print(y.shape)

(1797,)


In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [7]:
gb = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

In [8]:
gb.fit(X_train, y_train)

GradientBoostingClassifier(random_state=42)

In [9]:
gb_predictions = gb.predict(X_test)

In [10]:
accuracy = accuracy_score(y_test, gb_predictions)

cm = confusion_matrix(y_test, gb_predictions)

cf = classification_report(y_test, gb_predictions)

print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix: {cm}")
print(f"Classification Report: {cf}")

Accuracy: 0.9555555555555556
Confusion Matrix: [[35  0  0  0  0  0  0  0  1  0]
 [ 1 31  0  1  0  1  1  0  0  1]
 [ 0  0 34  0  0  0  0  0  1  0]
 [ 0  0  0 37  0  0  0  0  0  0]
 [ 1  0  0  0 35  0  0  0  0  0]
 [ 0  0  0  0  0 37  0  0  0  0]
 [ 0  0  0  0  0  0 34  0  2  0]
 [ 0  0  0  0  0  0  0 36  0  0]
 [ 0  2  0  0  0  0  0  0 32  1]
 [ 0  0  0  0  0  0  0  3  0 33]]
Classification Report:               precision    recall  f1-score   support

           0       0.95      0.97      0.96        36
           1       0.94      0.86      0.90        36
           2       1.00      0.97      0.99        35
           3       0.97      1.00      0.99        37
           4       1.00      0.97      0.99        36
           5       0.97      1.00      0.99        37
           6       0.97      0.94      0.96        36
           7       0.92      1.00      0.96        36
           8       0.89      0.91      0.90        35
           9       0.94      0.92      0.93        36

   

In [11]:
print(gb.feature_importances_)

[0.00000000e+00 9.64804905e-04 1.33715617e-02 5.05394989e-03
 2.73839092e-03 5.99671508e-02 6.86642927e-03 2.54117521e-03
 0.00000000e+00 3.59368575e-03 2.26092082e-02 7.23113952e-04
 3.48125884e-03 1.03914332e-02 2.56557119e-03 7.72136972e-04
 0.00000000e+00 1.42743642e-03 1.36895122e-02 2.94875569e-02
 3.33596288e-02 9.16732402e-02 2.21315763e-03 1.18829237e-04
 8.61323623e-06 4.07660404e-03 4.60692370e-02 1.83328644e-02
 3.26183436e-02 2.96107418e-02 9.30212581e-03 3.99292483e-04
 0.00000000e+00 6.11400398e-02 3.57465610e-03 4.77819008e-03
 7.34295345e-02 1.71761517e-02 1.80148171e-02 0.00000000e+00
 0.00000000e+00 6.85368858e-03 7.25332550e-02 6.81631294e-02
 1.18233959e-02 2.11810820e-02 1.90732652e-02 1.11394174e-04
 1.05040752e-10 3.26262576e-03 4.21055629e-03 1.79259942e-02
 1.15581160e-02 1.70543513e-02 1.93832805e-02 1.84347767e-04
 7.69775210e-04 4.51780740e-04 1.56920372e-02 2.95529594e-03
 4.55307648e-02 5.44054551e-03 2.30668460e-02 6.63402868e-03]


In [14]:
importance = pd.DataFrame({
    'feature': digits.feature_names,
    'importance': gb.feature_importances_
})
print(
    importance.sort_values(
        by='importance',
        ascending=False
    ).head(10)
)

      feature  importance
21  pixel_2_5    0.091673
36  pixel_4_4    0.073430
42  pixel_5_2    0.072533
43  pixel_5_3    0.068163
33  pixel_4_1    0.061140
5   pixel_0_5    0.059967
26  pixel_3_2    0.046069
60  pixel_7_4    0.045531
20  pixel_2_4    0.033360
28  pixel_3_4    0.032618
