In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import validation_curve
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [18]:
df = sns.load_dataset('titanic')

In [19]:
model = DecisionTreeClassifier(random_state=42)

In [9]:

X = df[[
    'pclass',
    'sex',
    'age',
    'sibsp',
    'parch',
    'fare',
    'embarked'
]]

y = df['survived']

In [10]:
numeric_features = [
    "age",
    'fare',
    'sibsp',
    'parch'
]

categorical_features = [
    'pclass',
    'sex',
    'embarked'
]

In [12]:

numeric_transformer = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())
    ]
)

categorical_transformer = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
        ('onehot', OneHotEncoder(handle_unknown='ignore'))
    ]
)

In [13]:
preprocessor = ColumnTransformer([
  ("num", numeric_transformer, numeric_features),
  ("cat", categorical_transformer, categorical_features)
])

In [20]:
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', model)
])

In [22]:
train_scores, validation_scores = validation_curve(
    estimator=model,
    X=X,
    y=y,
    param_name="classifier__max_depth",
    param_range=range(1, 21),
    cv=5,
    scoring="accuracy"
)

In [31]:
print(f"train scores: ", train_scores.mean(axis=1))

print(f"validation scores: ", validation_scores.mean(axis=1))



train scores:  [0.7867552  0.79461328 0.82463479 0.83641954 0.85213294 0.86531982
 0.88103125 0.89646454 0.9093717  0.92171786 0.93378351 0.94612887
 0.95595049 0.96352412 0.96913619 0.97362466 0.976711   0.97867532
 0.98035914 0.98176167]
validation scores:  [0.78673655 0.77331618 0.80919591 0.80364698 0.81144938 0.81594376
 0.80697382 0.81036972 0.81033833 0.80923357 0.79466449 0.78905907
 0.79241102 0.79017011 0.78118762 0.78343481 0.78118134 0.77893415
 0.78452702 0.76993911]


In [32]:
for depth, train, valid in zip(
    range(1,21),
    train_scores.mean(axis=1),
    validation_scores.mean(axis=1)
):
    print(
        f"Depth={depth:2d} | "
        f"Train={train:.3f} | "
        f"Validation={valid:.3f}"
    )


Depth= 1 | Train=0.787 | Validation=0.787
Depth= 2 | Train=0.795 | Validation=0.773
Depth= 3 | Train=0.825 | Validation=0.809
Depth= 4 | Train=0.836 | Validation=0.804
Depth= 5 | Train=0.852 | Validation=0.811
Depth= 6 | Train=0.865 | Validation=0.816
Depth= 7 | Train=0.881 | Validation=0.807
Depth= 8 | Train=0.896 | Validation=0.810
Depth= 9 | Train=0.909 | Validation=0.810
Depth=10 | Train=0.922 | Validation=0.809
Depth=11 | Train=0.934 | Validation=0.795
Depth=12 | Train=0.946 | Validation=0.789
Depth=13 | Train=0.956 | Validation=0.792
Depth=14 | Train=0.964 | Validation=0.790
Depth=15 | Train=0.969 | Validation=0.781
Depth=16 | Train=0.974 | Validation=0.783
Depth=17 | Train=0.977 | Validation=0.781
Depth=18 | Train=0.979 | Validation=0.779
Depth=19 | Train=0.980 | Validation=0.785
Depth=20 | Train=0.982 | Validation=0.770


In [33]:
from sklearn.model_selection import learning_curve

In [34]:
train_size, train_scores, validation_scores = learning_curve(
    estimator=model,
    X=X,
    y=y,
    cv=5,
    scoring="accuracy"
)

In [35]:
print(train_size)
print(train_scores)

[ 71 231 391 551 712]
[[0.98591549 1.         1.         1.         1.        ]
 [0.98268398 0.995671   0.995671   0.995671   0.995671  ]
 [0.97953964 0.99232737 0.98465473 0.98465473 0.98465473]
 [0.9800363  0.98729583 0.9800363  0.9800363  0.98185118]
 [0.98033708 0.98735955 0.98174157 0.98314607 0.97893258]]


In [38]:
print(train_size.mean())
print(train_scores.mean())

391.2
0.9879154965068375


In [39]:
print(validation_scores.mean())

0.7517607180967925
